FROM node:16-alpine as build
WORKDIR /app
copy . ./
COPY package*.json /

RUN npm install -g @angular/cli@15.1.2
RUN npm install
RUN ng build

COPY . .

FROM nginx:1.17.1-alpine
WORKDIR /app
COPY --from=build /app/dist/angular-starter-pack /usr/share/nginx/html
